name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest autopep8

    - name: Format Code
      run: |
        find . -name "*.py" -exec autopep8 --in-place --aggressive --aggressive {} +

    - name: Lint with Flake8
      run: flake8 .

    - name: Run tests
      run: pytest
